### ISSUE TITLE
Unable to archive after installing ZettaKit 0.03 via CocoaPods

### ISSUE THREAD

**Issue by benpackard** [zettajs/ZettaKit#11] opened 2016-01-17 17:31 UTC
A new project that installs ZettaKit 0.03 via CocoaPods will build for the simulator successfully but won't archive for distribution. Here's the test case:
- Create a new Xcode project
- Install ZettaKit 0.03 via CocoaPods:

```
//note: installing from 0.03 commit explicitly until 0.03 is published
pod 'ZettaKit', :git => 'https://github.com/zettajs/ZettaKit.git', :commit => '6f4f9a595c3e331901209df749db91de918818db'`
```
- Archive (Xcode: Product->Archive)

Expected: Project archives
Actual: 'ISpdy/ispdy.h' file not found`

Using ZettaKit 0.02 archives just fine. At first I thought this was a dependency issue - iSPDY is not listed in the ZettaKit pod spec's dependencies, and the example project is adding the dependency itself (and indeed archives successfully). But adding the dependency directly to my own test project did not resolve the issue. Then I realized that the example project is still pulling ZettaKit 0.02, so this isn't a valid test anyway.

**Comment by mdobson** [comment] 2016-01-17 17:41
Ah. I see. I can handle this next week. This is for a feature that was
specced out, but not relevant to your work. Should be a quick fix that I
can have merged in Monday early.

-Matt

_--_
_Matthew Dobson_ | _apigee https://apigee.com/_ | m: +1.734.634.5472 |
twitter @mdobs http://twitter.com/mdobs @apigee
https://twitter.com/apigee | _Apigee Community
http://community.apigee.com/_ for answers, ideas and support!

**Comment by benpackard** [comment] 2016-01-19 01:37
I pointed my podfile to `pod 'ZettaKit', :git => 'https://github.com/zettajs/ZettaKit.git', :commit => 'b224408ffa7b4e972e48d3ad8fdadf5b1de810d2'` but getting similar errors:

```
Undefined symbols for architecture x86_64:
  "_deflate", referenced from:
      -[ISpdyCompressor process:in:] in compressor.o
  "_deflateEnd", referenced from:
      -[ISpdyCompressor dealloc] in compressor.o
  "_deflateInit2_", referenced from:
      -[ISpdyCompressor init:withMode:] in compressor.o
  "_deflateSetDictionary", referenced from:
      -[ISpdyCompressor init:withMode:] in compressor.o
  "_inflate", referenced from:
      -[ISpdyCompressor process:in:] in compressor.o
  "_inflateEnd", referenced from:
      -[ISpdyCompressor dealloc] in compressor.o
  "_inflateInit2_", referenced from:
      -[ISpdyCompressor init:withMode:] in compressor.o
  "_inflateSetDictionary", referenced from:
      -[ISpdyCompressor process:in:] in compressor.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I believe this is reproducible from a new, empty project with the podfile above. Linking against my 0.02 fork for now so no hurry. Let me know if you need any more info.

**Comment by mdobson** [comment] 2016-01-19 13:42
I've found the issue. It's a bit deceptive. The iSPDY library requires zlib as a dependency. I've updated the podspec to include the library, and it started resolving the errors for me.

**Comment by benpackard** [comment] 2016-01-20 02:57
I don't see it in the podspec yet - I'm looking at commit 75cda2e815b7e7a6e87f774e5e3d6193990b19d0

**Comment by mdobson** [comment] 2016-01-20 17:08
Since it's an OS level library you have to use a different directive in the
podspec for including it. You should see `s.libraries = 'z'` in the file.
That should wire up everything with clang properly.

_--_
_Matthew Dobson_ | _apigee https://apigee.com/_ | m: +1.734.634.5472 |
twitter @mdobs http://twitter.com/mdobs @apigee
https://twitter.com/apigee | _Apigee Community
http://community.apigee.com/_ for answers, ideas and support!

**Comment by benpackard** [comment] 2016-01-21 13:52
Thanks, I see it. Still having some issues but I'm successfully building a new empty project that pulls in this podspec, so I think anything remaining is a config issue on my side. Will update when I can confirm.

**Comment by mdobson** [comment] 2016-01-21 13:53
Great. Keep me posted. I have one other potential fix, but it requires some
code removal.

-Matt

_--_
_Matthew Dobson_ | _apigee https://apigee.com/_ | m: +1.734.634.5472 |
twitter @mdobs http://twitter.com/mdobs @apigee
https://twitter.com/apigee | _Apigee Community
http://community.apigee.com/_ for answers, ideas and support!

**Comment by benpackard** [comment] 2016-01-21 16:11
I've managed to recreate my issue in an empty project:

1) Create a new Xcode project (mine is Swift, didn't test objc)
2) Install this branch of ZettaKit via cocoapods
3) `#import ZettaKit` in the main ViewController

As soon as I compile after step 3 I get `Could not build Objective-C module 'ZettaKit'` and `'include/ispdy.h' file not found`

I'm attaching a zip file with an example project.

[ZettaTest.zip](https://github.com/zettajs/ZettaKit/files/99421/ZettaTest.zip)

**Comment by mdobson** [comment] 2016-01-21 16:19
Thanks for the reproduction steps ben. Looks like there was a bad include. I've updated the repo. I'll go through your steps to confirm the fix.

**Comment by benpackard** [comment] 2016-01-21 16:37
Working well now, successfully builds, runs, and archives. Thanks again for the assistance.

**Closed as completed** 2016-02-19 18:47 UTC
